project:
  type: website
  output-dir: docs
  
website:
  title: "统计学25"
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: envelope
        href: lizongzhang9@qq.com
  page-footer:
    right: "Data illuminates insights."
    left: "&copy; Copyright 2025, Li Zongzhang"
format:
  html:
    theme: cerulean
    fontcolor: "#044875"
    toc: true
editor: source
execute:
  default-language: R


